### PR TITLE
Deps and release fix

### LINKED ISSUE #241: include insert-user tool in releases

### PR DESCRIPTION
**Pull request by cryptix**
fixes #241

### CODE REVIEW

**Comment by staltz** [comment]
Looks good :)

**Comment by cryptix** [comment]
Still need to build this on Linux to see if it works as intended (mostly see if the goreleaser change took as expected)

**Comment by arj03** [comment]
Would be terribly nice with a arm build for the next release to make it super easy to install on a pi :)

**Comment by staltz** [comment]
I marked this as a draft PR because https://github.com/ssb-ngi-pointer/go-ssb-room/pull/266#issuecomment-939360963 and to make it easier to manage outstanding PRs.

**Comment by decentral1se** [comment]
Oh, the rest are covered in https://github.com/ssbc/go-ssb-room/pull/291, we're good to close this then.

**Pull request closed without merging**
