### PR TITLE
Couple of documentation changes for Debian package

### LINKED ISSUE #324: Documentation - manually generate dhparams
Following through the installation docs (which are quite good, I might add) on an Ubuntu 22.04.1 server, there's one issue I ran into that I think might be worth mentioning.  certbot did not generate a dhparams file.  Maybe add an example command for generating that?  Something like:

```openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048```

### PR DESCRIPTION
**Pull request by KyleMaas**
Adds some clarifications for how to get started with go-ssb-room when installed from the Debian package.

Fixes #324 and #326

### CODE REVIEW

**Review by decentral1se — APPROVED** [review]

**Comment by macornwell** [comment]
I am finding that this insert-user command does not exist on a debian install. The file is nowhere to be found. (this is blocking me from getting this server up).

**Comment by KyleMaas** [comment]
Yeah, you have to follow the instructions under "First Admin user".  I added some supplementary directions in this change to make it more obvious how to follow those directions:

https://github.com/ssbc/go-ssb-room/pull/331/commits/c9adfee96fbd314b4c37c9062e0228a699c61ce6

**Comment by macornwell** [comment]
So you're saying I need to pull down the source code to build the utility? Gotcha. This should be made clearer. Normally if a person isn't building from source they aren't going to have the source code. (The advantage of a deb). Would certaintly be better if this utility was baked in via the deb.... (another time).

The other problem is that this cannot currently be built. (I know this isn't your problem). Just an FYI.

`build github.com/ssb-ngi-pointer/go-ssb-room/v2/cmd/insert-user: cannot load embed: malformed module path "embed": missing dot in first path element`

**Comment by KyleMaas** [comment]
It built for me.  But I agree - it should be included in the Debian package.  I ran into the same problem here:

https://github.com/ssbc/go-ssb-room/issues/327

Which ended up being a duplicate of:

https://github.com/ssbc/go-ssb-room/issues/241

This pull request is just about trying to help folks avoid some of the pitfalls I hit when I tried to install it.

**Comment by KyleMaas** [comment]
Thanks!

**Pull request merged**
